name: Gatsby deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          MICROCMS_API_KEY: ${{secrets.MICROCMS_API_KEY}}
          MICROCMS_ENDPOINT: ${{secrets.MICROCMS_ENDPOINT}}
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --prod
